### ISSUE TITLE
how to remove all rows using js

### ISSUE THREAD

**Issue by vishu-46** [unclead/yii2-multiple-input#113]
I try this one 

`$('#multiple-input').multipleInput('clear');`

but, this is not work

**Comment by unclead** [comment]
i checked it and it works for me. 
E.g. i called $('#examplemodel-schedule').multipleInput('clear') (see [this example](https://github.com/unclead/yii2-multiple-input/blob/master/examples/views/multiple-input.php)) and all rows was deleted

please prepare the code to reproduce an issue, otherwise i'm not able to help you

**Comment by unclead** [comment]
@vishu-46  did you solve a problem?
