### ISSUE TITLE
Update with input Embedded

### ISSUE THREAD

**Issue by FabianAguilar** [unclead/yii2-multiple-input#233]
Hello, I currently have a problem when using the nested input because it works perfect at the time of creating more does not work when it comes to update information because it is not loaded into the nested input, any idea of how to fix it?

My code in the form:

```
<?php
        
        echo MultipleInput::widget([
            'model' => $model,
            'attribute' => 'compromisosFormulario',
            'rendererClass' => \unclead\multipleinput\renderers\ListRenderer::className(),
            'addButtonOptions' => [
                'class' => 'btn-success btn-lg btnAgregarCompromiso',
            ],
            'removeButtonOptions' => [
                'class' => 'btn-danger btn-sm btnEliminarCompromiso'
            ],
            'columns' => [
                [
                    'name' => 'nombre',
                    'type' => 'textinput',
                    'title' => 'Nombre',
                ],
                [
                    'name' => 'entregablesFormulario',
                    'type' => MultipleInput::class,
                    'options' => [
                        'columns' => [
                            [
                                'name' => 'descripcion',
                                'type' => 'textinput'
                            ],
                        ]
                    ]
                ]
            ],
        ]);
        ?>
```

Relationships are , a contract has many commitments and ,a commitment has many deliverables

Code in the contract model using the variable 'compromisosFormulario' to fill the multiple input parent

```
public function afterFind() {
        parent::afterFind();
       //$this->compromisos is relationship with the commitement model
       $this->compromisosFormulario = $this->compromisos;
}
```
Code in the commitment model using the variable 'entregablesFormulario' to fill the multiple input children

```
public function afterFind() {
        parent::afterFind();
       //$this->compromisos is relationship with the deliverables model
        $this->entregablesFormulario = $this->entregables;
    }
```

Tanks!

**Comment by unclead** [comment]
@FabianAguilar is it still relevant?

**Comment by unclead** [comment]
@FabianAguilar show me the code how you handle an update of data (i mean your action or something where you handle it)

Because to be honest I didn't get the problem. As far as I see you assign relations data to virtual attributes in `afterFind` method and then you use these attributes inside the widget.

If you can describe step to reproduce the issue it would be great. For instance

1) create model with such attributes and relations
2) configure the widget
3) add a few rows and fill the following data
4) press submit and handle form data in such way
5) after save the data i expect to get the following but i get the following

The most difficult part of maintaining the widget is reproducing the issues and to be honest I'm not keen on it 😄

**Comment by unclead** [comment]
closed due inactivity of topic starter
