### ISSUE TITLE
BC broken: original model is required in nested MultipleInput

### ISSUE THREAD

**Issue by bscheshirwork** [unclead/yii2-multiple-input#266]
So... This variant

https://github.com/unclead/yii2-multiple-input/commit/d9b054229adae812062a1ebaec4318480b62c068

**is not working correctly**: 

MultipleInput stored model into `context` and check errors from this model. (And some other matters I think)

**Comment by bscheshirwork** [comment]
Reference at https://github.com/unclead/yii2-multiple-input/issues/249

May be

 just add a options for manual disable behavior `$model->{$this->name} = $value`?

**Comment by bscheshirwork** [comment]
#263

**Comment by unclead** [comment]
I found out how to make kartik's widgets work properly with default value (just add key `value` to `options` array and if this key is set kartik's widgets use it instead of getting value from a model )

f30a9b34d9d7bd4bc6bd346a4a6c4a0d1adad900

Of course it can break BC but it is impossible to check all available yii2 widgets.

**Comment by bscheshirwork** [comment]
I checked this widget itself. We need to rollout DynamicModel anyway.

**Comment by unclead** [comment]
if you check my commit you will notice that i removed usage of DynamicModel
