### ISSUE TITLE
How to use Yii models without JSON

### ISSUE THREAD

**Issue by alladas** [unclead/yii2-multiple-input#72]
Hi @unclead 
This seems great for many cases!
I wonder how to use existing Yii models to feed the widget?
I have tried the following without success.
It leads to a misconfiguration error => "Either 'name', or 'model' and 'attribute' properties must be specified."
 `$model = MyModel::find()->asArray()->all();`
`<?= $form->field($model, '{{%my-model}}')->widget(MultipleInput::className(),[
....
]
`

**Comment by unclead** [comment]
I guess you should use `TabularInput` instead of `MultipleInput`.

Here is an example of usage:
- action: https://github.com/unclead/yii2-multiple-input/blob/master/examples/actions/TabularInputAction.php
- model: https://github.com/unclead/yii2-multiple-input/blob/master/examples/models/Item.php
- view: https://github.com/unclead/yii2-multiple-input/blob/master/examples/views/tabular-input.php

**Comment by alladas** [comment]
Yes that is. You're right, I missed the TabularInput.
Great widgets! Thanks a lot.
